#!/bin/bash

#set -xe

d="${HOME}/Documents/screenshots"
ff="ss-"

mkdir -p "${d}"

n=$(find "${d}" -name "${ff}*" | wc -l)
n=$(printf "%05d" ${n})

ffmpeg -f x11grab -video_size 1920x1080 -i $DISPLAY -vframes 1 "${d}/${ff}${n}.png"
