#!/bin/bash

function f_vm_rdp() {
  if [ -z "${VM_USERNAME}" ]; then
    echo 'VM password (VM_USERNAME) not set'
    return 1
  fi

  if [ -z "${VM_PASSWORD}" ]; then
    echo 'VM password (VM_PASSWORD) not set'
    return 1
  fi

  (echo 'yes' | nohup rdesktop -K -k tr -a 8 -x m -u "${VM_USERNAME}" -p "${VM_PASSWORD}" localhost:5555 1>/dev/null 2>/dev/null) &
}

f_vm_rdp

